### ISSUE TITLE
OAuth 2 server should not be required to return "expires_in" attribute

### ISSUE THREAD

**Issue by ggtucker** [andreareginato/simple-oauth2#24] opened 2014-10-08 08:51 UTC
When making a request for an access token given an authorization code, it appears as though you're assuming the OAuth server is returning an expiration time. While that does follow the OAuth 2.0 protocol, I've found that some services don't bother with refresh tokens at all and instead have the client repeatedly request new access tokens when API requests need to be made (e.g. dev.battle.net).

Currently I'm receiving the following error in my code:

```
Access Token Error undefined

TypeError: Cannot read property 'expires_in' of null
    at Object.create (C:\projects\blizzcore\node_modules\simple-oauth2\lib\client\access-token.js:16:56)
    at saveToken (C:\projects\blizzcore\routes\login.js:45:29)
    at data (C:\projects\blizzcore\node_modules\simple-oauth2\lib\core.js:81:44)
    at Request._callback (C:\projects\blizzcore\node_modules\simple-oauth2\lib\core.js:23:7)
    at Request.self.callback (C:\projects\blizzcore\node_modules\simple-oauth2\node_modules\request\main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\projects\blizzcore\node_modules\simple-oauth2\node_modules\request\main.js:661:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\projects\blizzcore\node_modules\simple-oauth2\node_modules\request\main.js:623:14)
    at IncomingMessage.emit (events.js:117:20)
```
and I believe it has to do with the following code in lib/client/access-token.js (where it assumes the existence of ```token.expires_in```:
```
function create(token) {
  this.token = token;
  this.token.expires_at = (new Date).addSeconds(token.expires_in);
  return this;
}
```

My code looks like the following:
```
OAuth2.AuthCode.getToken({
  code: code,
  redirect_uri: 'https://localhost/callback'
}, saveToken);

function saveToken(error, result) {
  if (error) { console.log('Access Token Error', error.message); }
  token = OAuth2.AccessToken.create(result);
};

**Comment by SurenderLohia** [comment] 2015-09-03 12:46
@ggtucker I am get the same error.

@ggtucker, I am trying your workaround.  And I am getting this error:

```
TypeError: Cannot set property 'expires_in' of null
    at saveToken (/Users/surender/projects/oauth2/app.js:37:23)
    at data (/Users/surender/projects/oauth2/node_modules/simple-oauth2/lib/core.js:87:44)
    at Request._callback (/Users/surender/projects/oauth2/node_modules/simple-oauth2/lib/core.js:27:7)
    at Request.self.callback (/Users/surender/projects/oauth2/node_modules/simple-oauth2/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/surender/projects/oauth2/node_modules/simple-oauth2/node_modules/request/main.js:661:16)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/surender/projects/oauth2/node_modules/simple-oauth2/node_modules/request/main.js:623:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
```

**Comment by Spatlani** [comment] 2015-09-26 07:22
I've tried the workaround and it's not working for me, shows this error

**Comment by Spatlani** [comment] 2015-09-26 07:25
The workaround is not working for me, It's showing following error

```result.expires_in = 2592000;
TypeError: Cannot set property 'expires_in' of null```

**Comment by jonathansamines** [comment] 2015-10-09 03:28
Hi @Spatlani, are you checking for the "error" object received in the callback function? it seems like you are receiving an error from the lib, and since you ignore it and the token response is returning null, the token wrapper creation is failing. 

Let me know if this is the case, so we can close this as isn´t an error of this module.

**Comment by Spatlani** [comment] 2015-10-10 06:01
Yes you were right, It was fault in my code and I've fixed it, Thanks for the response

**Comment by jonathansamines** [comment] 2015-10-21 02:20
I´ll close this, since it´s unlikely to be a problem with this module. Feel free to reopen again if the problem is produced again.

**Closed by jonathansamines** 2015-10-21 02:20 UTC

**Comment by leonfs** [comment] 2015-12-07 10:27
Can I suggest to add the workaround on documentation/examples on README.md?

**Comment by MendeleyStack** [comment] 2015-12-07 13:13
Hey,

Create a pull request and I will be happy to add it. 

Thanks
