### ISSUE TITLE
Using with Webpack/enhanced-require

### ISSUE THREAD

**Issue by slavik-m** [andreareginato/simple-oauth2#41] opened 2015-07-02 09:53 UTC
In my project i use Webpack enhanced-require module with "hot load".

When I use code from simple-oauth2 docs like:

``` javascript
var oauth2 = require('simple-oauth2')({
  clientID: CLIENT_ID,
  clientSecret: CLIENT_SECRET,
  site: 'https://github.com/login',
  tokenPath: '/oauth/access_token'
});
```

I've got error message: 
```
TypeError: Cannot read property 'length' of undefined
    at Storage.finished (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:37:30)
    at SyncNodeJsInputFileSystem.stat (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/SyncNodeJsInputFileSystem.js:21:4)
    at Storage.provide (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:56:2)
    at CachedInputFileSystem.stat (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:126:20)
    at Tapable.<anonymous> (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:36:7)
    at Tapable.Resolver.forEachBail (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:171:3)
    at Tapable.<anonymous> (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:35:8)
    at Tapable.applyPluginsParallelBailResult (.../node_modules/enhanced-require/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:139:14)
    at Tapable.doResolve (.../node_modules/enhanced-require/node_modules/enhanced-resolve/lib/Resolver.js:49:15)
```

Do you have any idea how to use simple-oauth2 with this setup?

**Comment by andreareginato** [comment] 2015-07-13 17:12
Hi @slavik-m, unluckily I've no idea about your problem. Did you find out the solution?

**Comment by slavik-m** [comment] 2015-07-13 18:18
Hi @andreareginato. Unfortunately not. I wrote my custom solution.

**Comment by jonathansamines** [comment] 2015-10-09 03:59
Hi @slavik-m, this is unlikely to be a problem on this module. Seems like the enhanced-require have problems as loading some npm modules.  I´ll close this since we aren´t able to reproduce this.

**Closed by jonathansamines** 2015-10-09 03:59 UTC
Labels: invalid
